"""Genera el nuevo data/fortunes.json para MARU.

Reemplaza por completo las 817 fortunas actuales por un set nuevo con la
misma cantidad o más por categoría. Agrega categoría 'grosera' (sarcástica/
picante, sin insultos prohibidos por TikTok).

Salida: imprime el JSON canonicalizado a stdout. El llamador lo redirige
a `data/fortunes.json` y a las copias de `runtime_data` y `resources/data`.

Targets por categoría (count actual → nuevo):
    intro_templates  25 → 35
    good            104 → 120
    bad              89 → 100
    neutral          50 → 60
    specific         75 → 90
    philosophical    69 → 80
    love             45 → 55
    money            45 → 55
    health           45 → 55
    work             45 → 55
    gaming           50 → 60
    social           35 → 45
    creative         35 → 45
    mystery          35 → 45
    humor            35 → 45
    stream           20 → 30
    luck             20 → 30
    wisdom           20 → 30
    grosera (NUEVO)        80
    ─────────────────────────
    Total fortunas      1080  (vs 817)
    Total intros          35  (vs 25)
"""
from __future__ import annotations

import json
import sys

# ── Intros (35 — el {name} se sustituye en runtime) ────────────────────
INTROS = [
    "La fortuna de {name} para hoy dice:",
    "El destino de {name} revela:",
    "Las estrellas le dicen a {name}:",
    "La suerte de {name} anuncia:",
    "El universo le susurra a {name}:",
    "Los astros predicen para {name}:",
    "El oráculo revela a {name}:",
    "La bola de cristal muestra a {name}:",
    "Los espíritus ancestrales le dicen a {name}:",
    "El tarot místico revela para {name}:",
    "La luna llena predice para {name}:",
    "Las cartas del destino muestran a {name}:",
    "El cosmos tiene un mensaje para {name}:",
    "La sabiduría antigua habla a {name}:",
    "Los vientos del norte traen a {name}:",
    "El péndulo místico indica a {name}:",
    "Las runas ancestrales dicen a {name}:",
    "El espejo mágico refleja para {name}:",
    "Los dados del destino muestran a {name}:",
    "La niebla del tiempo revela a {name}:",
    "El libro de los secretos dice a {name}:",
    "Las voces del más allá susurran a {name}:",
    "El viento cósmico trae para {name}:",
    "La energía universal transmite a {name}:",
    "El guardián del destino anuncia a {name}:",
    "El reloj del destino marca para {name}:",
    "El búho sabio observa a {name} y declara:",
    "El humo del incienso dibuja para {name}:",
    "La llama de la vela parpadea y avisa a {name}:",
    "El gato negro cruza el camino de {name} y susurra:",
    "El espíritu del bosque le canta a {name}:",
    "Las profecías olvidadas resurgen para {name}:",
    "El portal del tiempo se abre para {name}:",
    "La voz interior de {name} sentencia:",
    "El eco del cosmos declara a {name}:",
]

# ── GOOD (120) ─────────────────────────────────────────────────────────
GOOD = [
    "Hoy es tu día de suerte, todo saldrá mejor de lo esperado",
    "Una sorpresa agradable llegará cuando menos lo esperes",
    "La fortuna sonríe a los valientes como tú",
    "Pronto recibirás noticias que alegrarán tu corazón",
    "Tu energía positiva atraerá cosas maravillosas",
    "Un encuentro especial cambiará tu perspectiva",
    "La abundancia está en camino hacia ti",
    "Tu esfuerzo será recompensado muy pronto",
    "Alguien importante piensa en ti en este momento",
    "Las puertas que se cerraron abrirán otras mejores",
    "Tu creatividad brillará y sorprenderá a todos",
    "Una oportunidad única tocará tu puerta",
    "El amor está más cerca de lo que crees",
    "Tu intuición te guiará al éxito",
    "Las estrellas están alineadas a tu favor",
    "Hoy descubrirás algo que te hará muy feliz",
    "Tu amabilidad regresará multiplicada",
    "Un viaje emocionante se aproxima en tu vida",
    "Tu talento será reconocido por las personas correctas",
    "La salud y vitalidad te acompañarán",
    "Una amistad valiosa se fortalecerá",
    "Recibirás un regalo inesperado del universo",
    "Tu paciencia dará frutos enormes",
    "El éxito te espera a la vuelta de la esquina",
    "Una idea brillante cambiará tu rumbo hoy",
    "Tu sonrisa contagiará a quienes te rodean",
    "Cosas buenas pasarán antes del fin de semana",
    "Una llamada inesperada te traerá alegría",
    "Vas a recibir una propuesta que aceptarás encantado",
    "Tu sueño más antiguo está por hacerse realidad",
    "El próximo mes traerá un gran avance personal",
    "Conocerás a alguien que cambiará tu historia",
    "Una vieja deuda con el universo se cobrará a tu favor",
    "Tu nombre saldrá en una buena conversación",
    "El dinero llegará desde una fuente que no esperabas",
    "Tu jefe o profesor notará tu esfuerzo",
    "Una segunda oportunidad aparecerá pronto",
    "Recuperarás algo que dabas por perdido",
    "Tu voz será escuchada donde antes no llegaba",
    "Hoy empieza una racha que no querrás que termine",
    "Lo que perdiste volverá con intereses",
    "Una semilla que plantaste hace tiempo florece hoy",
    "Tu lado más auténtico será admirado",
    "Un mensaje cariñoso te llegará esta semana",
    "Tu paciencia será reconocida con un milagro pequeño",
    "El tiempo está jugando a tu favor",
    "Una fiesta o celebración te espera",
    "Hoy verás señales claras del camino correcto",
    "Una persona importante hablará bien de ti",
    "Tu nombre estará en la mente de alguien especial",
    "Hoy resolverás un misterio que te atormentaba",
    "Una decisión arriesgada saldrá perfecta",
    "Tu cuenta bancaria sonreirá pronto",
    "Una invitación inesperada cambiará tu agenda",
    "Tendrás claridad sobre algo que te confundía",
    "Algo que pediste hace meses se materializará",
    "Tu esfuerzo se transformará en aplausos",
    "Hoy ganarás más de lo que invertiste",
    "Una persona poderosa abrirá una puerta para ti",
    "Recibirás una bendición disfrazada de coincidencia",
    "Tu paciencia será probada y aprobada",
    "El amor verdadero te buscará con un mensaje",
    "Tu creatividad será fuente de ingresos pronto",
    "Verás cumplido un deseo del año pasado",
    "Una mejora en la salud llegará sin medicina",
    "Tendrás más energía de la que esperabas hoy",
    "Una buena noticia familiar está cerca",
    "Tu rutina dará un giro positivo de la noche a la mañana",
    "Algo que dejaste a medias te dará éxito al retomarlo",
    "Recibirás un mensaje que te hará llorar de alegría",
    "Una idea simple te traerá fama o reconocimiento",
    "Tu generosidad será recompensada con una sorpresa",
    "Pronto te invitarán a algo que te encanta",
    "El próximo viernes guardará algo bueno para ti",
    "Una ganancia económica está marcada en el calendario",
    "Volverás a sentir esa chispa que extrañabas",
    "Una persona del pasado regresará para algo bueno",
    "Tu intuición acertará en una decisión clave",
    "Algo que querías comprar bajará de precio justo a tiempo",
    "Tendrás un momento que querrás recordar siempre",
    "Una racha de buena suerte arranca con la próxima semana",
    "El universo te está cobrando favores que olvidaste haber hecho",
    "Tu carisma estará a tope los próximos días",
    "Una amistad nueva florecerá rápido",
    "Recibirás un agradecimiento sincero que no esperabas",
    "Tu próximo riesgo será tu próximo logro",
    "Una idea que tuviste en la ducha te hará rico",
    "Tu siguiente compra te dará mucha satisfacción",
    "Te liberarás de un peso emocional muy pronto",
    "Una buena conversación te resolverá un dilema",
    "Hoy alguien hará algo bonito por ti sin pedirlo",
    "Tendrás un golpe de inspiración inolvidable",
    "Tu próxima publicación o post explotará",
    "Una etapa difícil termina y empieza una luminosa",
    "Tu esfuerzo silencioso será aplaudido en público",
    "Algo que quieres desde hace años entrará en oferta",
    "Una persona influyente seguirá tu trabajo de cerca",
    "Tu nombre aparecerá en un sorteo que vas a ganar",
    "Alguien que te quiere te dejará una sorpresa",
    "Recibirás un mensaje que te alegrará la semana",
    "Tu próxima foto será la mejor que te has tomado",
    "Una racha de buena salud te acompañará",
    "Tendrás un día casi perfecto antes del miércoles",
    "Un encuentro casual cambiará tu suerte por meses",
    "Lo que pediste con fe llega esta semana",
    "Tu trabajo será destacado por alguien importante",
    "Una vieja amistad volverá a tu vida sonriendo",
    "Recibirás una propuesta económica generosa",
    "Tu próxima decisión te hará sentir orgulloso",
    "Vas a vivir un momento mágico antes del fin de mes",
    "Un buen consejo cambiará tu manera de pensar",
    "Tu siguiente experiencia compartida te emocionará",
    "Algo que te negaron antes ahora será tuyo",
    "Una buena noche de sueño te resolverá la vida",
    "Tu energía hoy hará que pasen cosas buenas",
    "Tu intuición está más fina que nunca este mes",
    "Vas a brillar en un evento próximo",
    "Una ola de buena suerte arranca con tu próxima sonrisa",
    "Tu corazón encontrará calma muy pronto",
    "Lo que parecía imposible se va a cumplir",
    "Una nueva oportunidad llegará disfrazada de imprevisto",
    "Hoy es buen día para confiar en lo que sientes",
]
assert len(GOOD) >= 120, len(GOOD)

# ── BAD (100) ──────────────────────────────────────────────────────────
BAD = [
    "Hoy mejor no compres nada caro",
    "Una pequeña confusión arruinará un plan",
    "Cuidado con un mensaje mal interpretado",
    "Hoy no es día para tomar decisiones grandes",
    "Una persona te pedirá un favor que no querrás dar",
    "El tráfico o un retraso te robará tiempo",
    "Algo que dabas por hecho se complicará",
    "Tu paciencia será probada hasta el límite",
    "Un gasto inesperado tocará tu cuenta esta semana",
    "Una conversación se tornará incómoda sin querer",
    "Hoy las cosas no saldrán como las planeaste",
    "Mejor evita discutir con alguien terco",
    "Una promesa caerá en el olvido y te dolerá",
    "Algo que esperabas se va a postergar",
    "Una pequeña tontería te quitará la calma",
    "El cansancio te hará rendir menos hoy",
    "Una notificación arruinará un buen momento",
    "Tu autoestima necesitará cariño extra hoy",
    "Una persona te decepcionará con un gesto",
    "Hoy tropezarás con la misma piedra de antes",
    "Una invitación se cancelará a último momento",
    "Una vieja preocupación volverá a la mente",
    "Una llamada incómoda te buscará pronto",
    "Hoy alguien intentará robar tu tiempo",
    "Una frustración pequeña te quitará el ánimo",
    "Cuidado con creer rumores que escucharás",
    "Una decisión apresurada te costará un día",
    "Algo se va a romper en casa esta semana",
    "Un olvido te hará perder algo de dinero",
    "Hoy no es día para confiar en promesas vagas",
    "Una persona pedirá explicaciones que no esperabas",
    "Algo prestado regresará en mal estado",
    "Una tarea simple se volverá enredada",
    "Una mentira piadosa se volverá en tu contra",
    "Cuidado con discutir por mensajes hoy",
    "Un retraso te complicará la jornada",
    "Hoy una alarma o notificación te traicionará",
    "Una vieja deuda emocional pedirá ser pagada",
    "Tu energía bajará a media tarde sin aviso",
    "Una persona del pasado escribirá para incomodarte",
    "Cuidado con lo que firmas o aceptas hoy",
    "Una compra impulsiva traerá arrepentimiento",
    "Una amistad pedirá distancia sin explicación",
    "El clima va a arruinar un plan hoy",
    "Una palabra de más romperá un acuerdo",
    "Un proyecto se quedará en pausa esta semana",
    "Hoy se nota que dormiste mal, descansa más",
    "Una crítica te dolerá más de lo justo",
    "Un mensaje viejo aparecerá en mal momento",
    "Tu paciencia volará por una tontería diminuta",
    "Algo importante se demorará en aprobarse",
    "Una distracción te hará perder algo en el camino",
    "Hoy la balanza no estará de tu lado",
    "Un error tipográfico te dará vergüenza",
    "Algo que enviaste se perderá en el camino digital",
    "Una persona prometerá ayudarte y no lo hará",
    "Una pequeña enfermedad te visitará brevemente",
    "Hoy tendrás ganas de quejarte de todo",
    "Un tropezón con un familiar pedirá una disculpa",
    "El internet o el celular te jugará una mala broma",
    "Una decisión postergada empeorará el problema",
    "Hoy un alimento te caerá pesado",
    "Una conversación importante se enredará",
    "Un compromiso de última hora arruinará tu plan",
    "Hoy no es día para presumir nada",
    "Cuidado con dar tu palabra a la ligera",
    "Una persona con mala vibra cruzará tu día",
    "Hoy te sentirás invisible en un grupo",
    "Algo guardado se va a perder por descuido",
    "Una idea brillante se la robará otra persona",
    "Vas a olvidar algo importante esta semana",
    "Una broma será tomada como ofensa",
    "Cuidado con responder mensajes de madrugada",
    "Una mala noticia llegará disfrazada de buena",
    "Hoy te lloverá sobre mojado, paciencia",
    "Un viejo conflicto se reactivará sin razón",
    "Vas a pagar dos veces por algo si no revisas",
    "Una espera larga te pondrá de mal humor",
    "Algo en la calle te asustará por unos segundos",
    "Una conversación familiar tocará un tema delicado",
    "Hoy las ganas no te van a alcanzar",
    "Vas a dudar de una decisión ya tomada",
    "Una vieja foto incómoda saldrá a la luz",
    "Cuidado con una caída tonta esta semana",
    "Una promesa propia se te hará cuesta arriba",
    "Hoy la motivación llegará tarde, pero llegará",
    "Algo que ordenaste va a tardar más de lo dicho",
    "Una contraseña olvidada te complicará el día",
    "Cuidado con perder algo en transporte público",
    "Un mensaje doble sentido causará confusión",
    "Hoy te pesará más la cabeza que el cuerpo",
    "Una factura llegará más alta de lo esperado",
    "Vas a chocar con una pared por mirar el celular",
    "Una persona envidiosa lanzará una indirecta",
    "Hoy un electrodoméstico va a fallar sin aviso",
    "Tu humor estará nublado al despertar",
    "Cuidado con un plato que se te puede caer",
    "Vas a olvidar tu cargador justo cuando lo necesites",
    "Una espera médica o burocrática se hará larga",
    "Hoy una promesa romántica caerá en saco roto",
    "Una persona impuntual te dejará plantado",
    "Cuidado con prometer algo que no podrás cumplir",
]
assert len(BAD) >= 100, len(BAD)

# ── NEUTRAL (60) ───────────────────────────────────────────────────────
NEUTRAL = [
    "Hoy será un día tranquilo, sin grandes sorpresas",
    "Las cosas seguirán su curso natural sin cambios",
    "Es un buen momento para reflexionar con calma",
    "El equilibrio será la palabra clave de tu día",
    "Mantén tu rutina y todo fluirá en orden",
    "Pequeños cambios traerán grandes resultados",
    "La paciencia será tu mejor aliada hoy",
    "Observa antes de actuar, las señales son sutiles",
    "Un día normal puede tener belleza si la buscas",
    "Sigue tu instinto, te llevará a buen puerto",
    "Hoy es día de ahorrar energía para mañana",
    "No fuerces nada, déjalo madurar a su tiempo",
    "Tu capacidad de adaptarte será suficiente",
    "Una conversación común te dará un dato útil",
    "Hoy la magia está en los detalles pequeños",
    "Camina sin prisa, vas en la dirección correcta",
    "El silencio te dirá más que mil palabras hoy",
    "Mantén la calma cuando todo parezca lento",
    "Un día sin novedades también es ganancia",
    "Tu jornada será un espejo de tu actitud",
    "Si haces lo de siempre, recibirás lo de siempre",
    "Es buen día para limpiar, ordenar y clasificar",
    "Tu cuerpo te pedirá agua y descanso, escúchalo",
    "Hoy ni demasiado bien ni demasiado mal, en el medio",
    "Una pequeña victoria valdrá tanto como una grande",
    "Un día gris afuera puede ser luminoso adentro",
    "Las cosas se acomodan solas si dejas espacio",
    "Hoy ningún plan es mejor que un mal plan",
    "Aprende algo nuevo aunque sea diminuto",
    "Tu rutina necesita un toque distinto hoy",
    "Vive el presente, no lo aceleres",
    "Sembrarás ahora lo que cosecharás en semanas",
    "Una decisión pequeña hoy abrirá una puerta luego",
    "Hoy es un día para escuchar más que hablar",
    "El universo te pide sólo perseverancia",
    "Camina, respira, y todo se va aclarando",
    "Tu mente necesita descanso más que estímulo",
    "Hoy un dato suelto encajará con otro viejo",
    "Es buen momento para revisar tus prioridades",
    "El día te exigirá menos de lo que crees",
    "Hoy no es día de pelear, es día de observar",
    "Tu lista de pendientes se acortará casi sola",
    "Algo que pensabas urgente puede esperar",
    "Hoy vale más la calma que la velocidad",
    "Una conversación neutra te dará claridad",
    "El día tendrá un ritmo lento, acéptalo",
    "Una pausa breve te devolverá productividad",
    "Hoy todo está como debe estar, no exijas más",
    "Una pequeña rutina romperá la monotonía",
    "El balance entre dar y recibir será visible hoy",
    "Tu energía no será alta, pero tampoco baja",
    "Un café o un té te alinearán el día",
    "Hoy es buen día para pasar desapercibido",
    "El silencio interno te dirá hacia dónde ir",
    "Una caminata corta cambiará tu humor",
    "Hoy elegir bien es mejor que elegir rápido",
    "Tu intuición trabajará en silencio hoy",
    "El día te recompensará si no lo apuras",
    "Hoy el mundo se mueve, tú observas con sabiduría",
    "Mantén el ritmo lento, mañana acelerás",
]
assert len(NEUTRAL) >= 60, len(NEUTRAL)

# ── SPECIFIC (90) ──────────────────────────────────────────────────────
SPECIFIC = [
    "Recibirás un mensaje de WhatsApp que cambiará tu día",
    "Una persona con tu mismo signo te dará un consejo clave",
    "Antes del jueves verás algo que te hará sonreír mucho",
    "El número 7 traerá suerte hoy, prestale atención",
    "Una canción aleatoria te marcará el ánimo del día",
    "Una persona con remera roja te dará una buena noticia",
    "Tu próximo café o mate sabrá mejor que de costumbre",
    "Verás dos veces el mismo número en una hora",
    "Una notificación te alegrará la tarde",
    "Hoy el clima jugará a tu favor en un momento clave",
    "Encontrarás una moneda en el camino antes del sábado",
    "Un sueño confuso te traerá una respuesta clara",
    "Recibirás un like que te hará sonreír mucho",
    "Antes del mediodía sabrás algo que esperabas",
    "Un desconocido te hará un cumplido honesto",
    "Mañana empezará con una buena noticia familiar",
    "Una mascota o animal cruzará tu mirada y traerá suerte",
    "El próximo lunes empezarás algo nuevo importante",
    "Una vieja foto te recordará un momento dorado",
    "Verás una luna especial esta semana",
    "Una persona morena hablará bien de ti hoy",
    "Una persona rubia te buscará con buenas intenciones",
    "Tu próximo viaje en transporte será memorable",
    "Una conversación en la calle cambiará tu día",
    "Recibirás una invitación a un evento social",
    "Un familiar lejano se acordará de ti pronto",
    "Tu próxima compra online llegará antes de tiempo",
    "Antes del próximo domingo recibirás dinero extra",
    "Un correo electrónico cambiará tu agenda",
    "Una llamada corta resolverá un tema pendiente",
    "Una persona con anteojos te dará un consejo útil",
    "Verás caer una estrella esta noche, pide un deseo",
    "Una pequeña planta en tu casa florecerá pronto",
    "Antes del próximo miércoles recibirás un agradecimiento",
    "Encontrarás algo que perdiste hace meses",
    "Una vieja contraseña te volverá a la mente justo a tiempo",
    "Una canción romántica te recordará algo lindo",
    "Tu próximo Uber o taxi traerá una conversación curiosa",
    "Una persona alta te ayudará en algo importante",
    "Verás una matrícula con tres números iguales hoy",
    "Una persona te enviará un audio largo que vale escuchar",
    "Tu próxima compra de comida será deliciosa",
    "Una moneda antigua aparecerá en tu bolsillo",
    "Antes del fin de semana firmarás algo positivo",
    "Una persona te abrazará justo cuando lo necesites",
    "Tu próximo entrenamiento físico se sentirá ligero",
    "Una conversación con un niño te dejará una lección",
    "Antes del próximo martes recibirás una propuesta laboral",
    "Una vieja amistad subirá una historia que te alegrará",
    "Una persona del pasado dejará de molestarte para siempre",
    "Tu próxima reunión saldrá mejor de lo esperado",
    "Antes del próximo viernes una sorpresa golpeará tu puerta",
    "Una persona con voz suave te calmará el día",
    "Verás un pájaro o ave que te traerá paz",
    "Una pequeña casualidad será una señal del cosmos",
    "Tu próxima publicación tendrá más alcance que nunca",
    "Una persona te enviará una foto que te alegrará",
    "Antes de las próximas 48 horas recibirás un favor",
    "Una vieja deuda económica se cerrará pronto",
    "Una decisión tomada hace un año te dará frutos esta semana",
    "Una persona con cabello largo te dará una sorpresa",
    "Una notificación de la mañana te marcará el ánimo",
    "Un dato curioso que escuchas hoy te servirá luego",
    "Recibirás un meme que te hará reír a carcajadas",
    "Una persona que admiras te responderá un mensaje",
    "Tu próximo desayuno será especialmente bueno",
    "Una persona te dirá lo que necesitabas escuchar",
    "Antes del miércoles encontrarás algo brillante",
    "Tu siguiente amistad nueva durará años",
    "Una vieja canción te traerá nostalgia bonita",
    "Una persona joven te enseñará algo nuevo",
    "Una persona mayor te dará un consejo de oro",
    "Verás un arcoíris esta semana, será buena señal",
    "Una luz parpadeará justo cuando tomes una decisión",
    "Antes del próximo lunes recibirás un piropo bonito",
    "Una persona del trabajo o estudio te buscará para algo bueno",
    "Tu próximo encuentro casual será con alguien especial",
    "Una vieja prenda te quedará mejor que antes",
    "Antes del próximo jueves alguien te dirá te quiero",
    "Tu próxima carta o paquete tendrá una sorpresa",
    "Una persona con perro te cruzará en buen momento",
    "Verás una nube con forma especial, será una señal",
    "Una conversación nocturna te traerá claridad",
    "Antes del fin de mes una puerta inesperada se abrirá",
    "Una persona con sentido del humor te alegrará la semana",
    "Tu próxima foto saldrá perfecta sin filtros",
    "Una vieja receta familiar te volverá a sorprender",
    "Una persona con misma profesión te abrirá una puerta",
    "Tu siguiente mensaje recibido será de alguien que extrañabas",
    "Una persona que viste hoy aparecerá otra vez en una semana",
    "Antes del próximo miércoles te ocurrirá una coincidencia mágica",
]
assert len(SPECIFIC) >= 90, len(SPECIFIC)

# ── PHILOSOPHICAL (80) ─────────────────────────────────────────────────
PHILOSOPHICAL = [
    "El que controla su mente, controla su destino",
    "La paciencia es la madre de todas las victorias",
    "El silencio enseña lo que las palabras callan",
    "Lo que resistes, persiste; lo que aceptas, se transforma",
    "Cada final esconde una semilla nueva",
    "Quien camina despacio, llega a todas partes",
    "La verdad no se grita, se sostiene",
    "El que se conoce a sí mismo, no se pierde en otros",
    "Toda tormenta enseña algo a quien la cruza",
    "El alma reconoce lo verdadero antes que la mente",
    "El presente es el único lugar donde existe la vida",
    "Lo que ofreces al mundo, regresa multiplicado",
    "Cada herida bien curada se vuelve fortaleza",
    "La libertad empieza al soltar lo que no era tuyo",
    "El que perdona libera dos personas a la vez",
    "El miedo y el amor no caben en el mismo pensamiento",
    "El que escucha aprende, el que habla repite",
    "La calma es la velocidad del sabio",
    "Tu energía es tu lenguaje más honesto",
    "Lo que dejas ir te enseña tu verdadero tamaño",
    "Cada día es un examen de quién quieres ser",
    "El que cuida sus pensamientos cosecha su realidad",
    "La gratitud es el imán más antiguo del universo",
    "El que se queja, dilata; el que actúa, transforma",
    "El éxito sin paz interior es solo un disfraz",
    "El alma no envejece, se profundiza",
    "La sabiduría no se enseña, se contagia",
    "Cada elección dibuja la persona que vas a ser",
    "El que entiende sus errores los convierte en mapas",
    "El amor verdadero no exige, sostiene",
    "Lo simple es lo último que entendemos",
    "La fuerza del agua no es su dureza, es su constancia",
    "Cuando bajas el ruido, escuchas la respuesta",
    "El que sirve sin esperar es el más libre",
    "Quien acepta el cambio, abraza la vida",
    "El verdadero viaje es hacia adentro",
    "Cada relación es un espejo, no una jaula",
    "El conocimiento abre puertas, la sabiduría las cuida",
    "El que cree que no tiene tiempo es esclavo de su agenda",
    "Lo que repites en silencio, te define en voz alta",
    "El descanso no es debilidad, es preparación",
    "Toda decisión es un voto a favor de quién serás",
    "El que se queda quieto en la tormenta, sobrevive",
    "El alma habla bajito, hay que aprender a escucharla",
    "La compasión es la última frontera de la valentía",
    "El que ama de lejos, ama mejor",
    "La duda enseña tanto como la certeza",
    "El que se ríe de sí mismo nunca pierde",
    "El verdadero poder es no necesitar demostrarlo",
    "La intuición es memoria del alma",
    "Cada vez que sueltas, ganas espacio",
    "La quietud es el laboratorio de las mejores ideas",
    "El que sirve también es servido en silencio",
    "El amor propio es el cimiento de toda decisión sana",
    "Quien sabe esperar, sabe vivir",
    "La belleza vive en los detalles que nadie obliga a notar",
    "El miedo señala dónde está el crecimiento",
    "El que abraza sus contradicciones se vuelve completo",
    "Cada paso firme deshace cien pasos perdidos",
    "El presente bien vivido cura el pasado",
    "Tu vida es la suma de las cosas que dejas entrar",
    "El que se compara, pierde; el que se admira, crea",
    "La fe no es certeza, es elección diaria",
    "Lo que callas también te define",
    "Cada acto cotidiano es una pequeña ceremonia",
    "El que hace las paces consigo mismo gana al mundo",
    "El silencio entre dos personas dice más que un libro",
    "El que aprende a decir no, multiplica su sí",
    "El alma necesita arte como el cuerpo necesita pan",
    "Lo eterno se construye en lo cotidiano",
    "El que ama sin condición, vibra distinto",
    "Cada mañana es una invitación a renacer",
    "El que descansa con conciencia rinde el doble",
    "La felicidad es un estado, no un destino",
    "Lo que entregas con alegría regresa con belleza",
    "El que mide su vida en presencia, no en logros, gana",
    "Cada relación importante es un pacto con tu evolución",
    "El que confía en el proceso no necesita controlar todo",
    "La paz es el verdadero lujo del siglo",
    "El que cultiva su jardín interior, perfuma a otros",
    "Tu mayor herencia será la calidad de tus decisiones",
]
assert len(PHILOSOPHICAL) >= 80, len(PHILOSOPHICAL)

# ── LOVE (55) ──────────────────────────────────────────────────────────
LOVE = [
    "Alguien sueña contigo justo en este momento",
    "Una vieja chispa volverá a encenderse pronto",
    "El amor está más cerca de lo que crees",
    "Una mirada cambiará tu corazón esta semana",
    "Esa persona también está pensando en ti",
    "Una conversación romántica te dejará sin palabras",
    "Un mensaje cariñoso te alegrará la noche",
    "Pronto recibirás una declaración inesperada",
    "Tu próxima cita será mucho mejor que la anterior",
    "Una amistad cercana esconde un amor secreto",
    "El universo te está preparando para alguien especial",
    "Una vieja relación quedará completamente sanada",
    "Recibirás un detalle que te derretirá",
    "Tu pareja o crush mostrará un lado nuevo y bonito",
    "Una pelea pequeña terminará en un abrazo grande",
    "Pronto sentirás mariposas otra vez",
    "Un viaje en pareja está más cerca de lo que parece",
    "Una persona del pasado pedirá perdón sinceramente",
    "Tu próximo flechazo será diferente y duradero",
    "Una velada inesperada terminará en romance",
    "El amor te llegará disfrazado de amistad",
    "Una invitación a salir te tomará por sorpresa",
    "Tu sonrisa va a conquistar a alguien sin querer",
    "Una persona discreta confesará lo que siente por ti",
    "Tu corazón sanará una herida vieja esta semana",
    "Un beso inesperado cambiará el rumbo del mes",
    "Una persona se enamorará de tu manera de ser",
    "Tu lenguaje del amor coincidirá con el de alguien especial",
    "Un viejo crush te buscará con buenas intenciones",
    "Una conversación profunda iniciará algo bonito",
    "Tu próxima primera cita te dejará volando",
    "Recibirás una flor o detalle inesperado",
    "Una persona protectora aparecerá en tu vida",
    "Tu confianza romántica se va a recuperar pronto",
    "Una sorpresa de pareja te emocionará hasta las lágrimas",
    "El amor que pediste vendrá tranquilo, no a los gritos",
    "Una distancia amorosa empezará a acortarse",
    "Una vieja foto te hará entender lo que querías",
    "Tu próxima relación durará lo que vos quieras",
    "Una persona dejará de jugar contigo y se animará",
    "El amor llegará el día que dejes de buscarlo",
    "Una nueva amistad esconde un amor en proceso",
    "Tu pareja o crush hará algo que te dejará feliz",
    "Una canción te recordará a esa persona y le escribirás",
    "Una mirada cruzada en la calle te dejará pensando",
    "Tu próxima conexión será fuerte y respetuosa",
    "Vas a recibir un te quiero que esperabas hace meses",
    "Una persona aprenderá a amarte como mereces",
    "El amor propio te abrirá la puerta del amor de pareja",
    "Una conversación pendiente terminará en reconciliación",
    "Tu corazón estará protegido por una buena energía",
    "Vas a salir de una zona gris romántica",
    "Una persona te elegirá una y otra vez",
    "Tu siguiente romance será digno de una película",
    "Recibirás un detalle simple que valdrá oro",
]
assert len(LOVE) >= 55, len(LOVE)

# ── MONEY (55) ─────────────────────────────────────────────────────────
MONEY = [
    "Pronto recibirás un dinero extra que no esperabas",
    "Una propina o bonus te alegrará la semana",
    "Una idea sencilla te traerá ingresos pronto",
    "Vas a cobrar algo pendiente antes del fin de mes",
    "Un trabajo extra aparecerá sin buscarlo",
    "Una persona te pagará una deuda olvidada",
    "Una compra inteligente hoy te ahorrará mucho",
    "Tu próxima venta será más grande que las anteriores",
    "El dinero llegará por una vía nueva",
    "Una promoción o ascenso está más cerca de lo que crees",
    "Vas a encontrar un descuento perfecto para algo que querías",
    "Tu cuenta bancaria sonreirá con una transferencia",
    "Un familiar te ayudará económicamente sin pedírselo",
    "Tu próximo cliente o jefe será generoso",
    "Una inversión pequeña traerá un retorno bonito",
    "Una factura llegará más baja de lo esperado",
    "Vas a recuperar dinero que dabas por perdido",
    "Un proyecto paralelo se volverá tu fuente principal",
    "Una idea creativa te dará ingresos en poco tiempo",
    "Tu suerte económica está mejorando lentamente",
    "Una nueva oportunidad de negocio tocará la puerta",
    "Pronto firmarás un acuerdo económico ventajoso",
    "Vas a vender algo viejo por un buen precio",
    "Tu próximo mes traerá una mejora financiera notable",
    "Una recomendación tuya te traerá una comisión",
    "Vas a cobrar un trabajo postergado",
    "Una herencia o regalo monetario está en camino",
    "Un viaje no planeado se pagará casi solo",
    "Una persona influyente abrirá una puerta económica",
    "Tu próxima entrevista o reunión irá excelente",
    "Una habilidad tuya valdrá más dinero del que crees",
    "Vas a aprender a ahorrar sin sufrirlo",
    "Una compra postergada por fin será posible",
    "Tu próximo pago será más alto que el anterior",
    "Vas a cerrar un trato muy beneficioso esta semana",
    "Tu cuenta de ahorros crecerá más rápido este mes",
    "Una idea nocturna te dará un negocio claro",
    "Una alianza con otra persona multiplicará ganancias",
    "Vas a recibir una propuesta económica formal",
    "Tu próximo viaje será más barato de lo planeado",
    "Una persona te enseñará un truco para ahorrar",
    "Vas a tomar una decisión financiera inteligente",
    "Una deuda grande se reducirá inesperadamente",
    "Tu próximo cliente repetirá y traerá otros",
    "Una rifa, sorteo o azar te favorecerá pronto",
    "Vas a recuperar gastos de un viaje viejo",
    "Tu próxima compra online tendrá un descuento secreto",
    "Una pequeña fortuna se va a estabilizar en tu vida",
    "Vas a recibir un cheque o transferencia esta semana",
    "Tu trabajo será valorado con un aumento",
    "Una colaboración pagará mejor que tu trabajo principal",
    "Vas a aprender a invertir mejor que tus amigos",
    "Una idea simple multiplicará tus ingresos",
    "Vas a entender el valor real de tu tiempo",
    "Una próxima factura tendrá un error a tu favor",
]
assert len(MONEY) >= 55, len(MONEY)

# ── HEALTH (55) ────────────────────────────────────────────────────────
HEALTH = [
    "Tu energía aumentará en los próximos días",
    "Una rutina nueva te devolverá vitalidad",
    "Vas a sentirte más liviano esta semana",
    "Tu cuerpo te pedirá más agua, escúchalo",
    "Una caminata diaria te cambiará el ánimo",
    "Una buena noche de sueño te reseteará por completo",
    "Tu salud mental se va a equilibrar pronto",
    "Vas a respirar con más profundidad y claridad",
    "Un pequeño dolor desaparecerá sin tratamiento",
    "Tu sistema inmune se va a fortalecer",
    "Vas a comer mejor sin esfuerzo esta semana",
    "Tu postura mejorará al prestarle atención",
    "Una práctica de meditación te traerá calma",
    "Tu pelo o piel mostrarán cambios positivos",
    "Vas a descansar mejor que en los últimos meses",
    "Tu cuerpo va a pedirte naturaleza, ve",
    "Una comida casera te alegrará el cuerpo",
    "Vas a cuidar mejor tus horarios de sueño",
    "Una nueva actividad física te enganchará rápido",
    "Tu humor se va a estabilizar en pocos días",
    "Vas a sentir el cuerpo más flexible y fuerte",
    "Tu próximo chequeo médico saldrá bien",
    "Una respiración profunda te alineará el día",
    "Vas a perder ese cansancio crónico pronto",
    "Tu cuerpo agradecerá un día sin pantallas",
    "Una tarde de descanso valdrá una semana de gym",
    "Vas a notar más energía al despertar",
    "Tu mente se va a aclarar después de un buen sueño",
    "Una conversación honesta te liberará la espalda",
    "Vas a estabilizar tu peso de forma natural",
    "Tu hidratación va a mejorar y se notará",
    "Una rutina mañanera te cambiará el día",
    "Vas a sentirte orgulloso de tu cuerpo esta semana",
    "Tu mente se calmará con una práctica diaria",
    "Vas a dormir como hace tiempo no dormías",
    "Tu cuerpo va a responder mejor al ejercicio",
    "Una mejora visible aparecerá pronto en tu piel",
    "Vas a recuperar energía con una siesta corta",
    "Tu autoestima física dará un salto positivo",
    "Una vieja molestia desaparecerá sin aviso",
    "Vas a comer más liviano y sentirte mejor",
    "Tu cuerpo te enseñará una lección importante",
    "Vas a romper un mal hábito esta semana",
    "Tu próxima sesión de ejercicio se sentirá fácil",
    "Una nueva amistad te impulsará a moverte más",
    "Vas a notar mejoras al levantarte temprano",
    "Tu cuerpo te lo agradecerá si bajas el azúcar",
    "Una pequeña pausa cambiará tu productividad",
    "Vas a redescubrir un deporte que te gustaba",
    "Tu mente y cuerpo van a sincronizarse mejor",
    "Vas a tener más ganas de cocinar saludable",
    "Tu sistema digestivo se aliviará esta semana",
    "Una pequeña mejora será notada por otros",
    "Vas a descubrir un té o fruta que te encantará",
    "Tu próximo despertar será mucho más liviano",
]
assert len(HEALTH) >= 55, len(HEALTH)

# ── WORK (55) ──────────────────────────────────────────────────────────
WORK = [
    "Tu jefe notará tu esfuerzo esta semana",
    "Una promoción está más cerca de lo que crees",
    "Vas a recibir un cumplido profesional importante",
    "Tu próximo proyecto será un éxito rotundo",
    "Una reunión clave saldrá a tu favor",
    "Vas a destacar entre tus compañeros pronto",
    "Una idea tuya cambiará el curso de un proyecto",
    "Tu trabajo será reconocido públicamente",
    "Vas a aprender una nueva habilidad muy rápido",
    "Una oportunidad laboral fuera de tu zona aparecerá",
    "Vas a cerrar un trato muy beneficioso",
    "Tu networking dará frutos esta semana",
    "Un mentor inesperado te dará un consejo de oro",
    "Vas a sentirte alineado con lo que haces",
    "Tu próxima entrevista será un sí seguro",
    "Una presentación tuya impresionará al equipo",
    "Vas a tener un día súper productivo el viernes",
    "Tu agenda se reorganizará a tu favor",
    "Una colaboración nueva te traerá grandes resultados",
    "Vas a recibir un mensaje de un reclutador",
    "Una ascensión silenciosa empezará pronto",
    "Tu marca personal crecerá rápido en breve",
    "Una vieja propuesta laboral volverá con mejores condiciones",
    "Vas a recibir un correo importante esta semana",
    "Tu liderazgo se va a notar en una crisis menor",
    "Una capacitación te abrirá puertas nuevas",
    "Vas a tener una conversación clave con tu jefe",
    "Tu rendimiento sorprenderá hasta a vos mismo",
    "Una decisión profesional valiente saldrá bien",
    "Vas a recuperar ganas de tu trabajo actual",
    "Tu creatividad será la diferencia este mes",
    "Una idea simple te ahorrará horas de trabajo",
    "Vas a cerrar una etapa laboral con elegancia",
    "Tu próximo cambio de rol se hará sin estrés",
    "Una herramienta nueva mejorará tu día a día",
    "Vas a aprender a delegar mejor",
    "Tu enfoque se afinará en los próximos días",
    "Un cliente difícil cambiará de actitud",
    "Vas a inspirar a alguien en tu equipo sin saberlo",
    "Tu carrera dará un salto antes de seis meses",
    "Una colaboración remota te traerá ingresos",
    "Vas a equilibrar mejor el trabajo con tu vida",
    "Tu siguiente jefe será mucho mejor que el anterior",
    "Una oferta laboral inesperada llegará pronto",
    "Vas a entregar a tiempo un proyecto difícil",
    "Tu nombre será mencionado en una buena reunión",
    "Una propuesta tuya será aceptada sin cambios",
    "Vas a cerrar tratos con personas honestas",
    "Tu organización dará un salto este mes",
    "Una persona mayor te dará un consejo profesional clave",
    "Vas a abandonar una tarea que te quitaba energía",
    "Tu enfoque te traerá resultados visibles pronto",
    "Una alianza profesional duradera está por nacer",
    "Vas a recuperar la pasión por algo que dabas por muerto",
    "Tu próxima semana laboral será mucho más liviana",
]
assert len(WORK) >= 55, len(WORK)

# ── GAMING (60) ────────────────────────────────────────────────────────
GAMING = [
    "Hoy ganarás más partidas de las que pierdas",
    "Tu próximo loot tendrá un drop legendario",
    "Vas a hacer un clutch épico en una partida ranked",
    "Tu puntería estará especialmente afilada hoy",
    "Una invitación a jugar con buenos jugadores llegará",
    "Vas a subir de rango antes del fin de semana",
    "Tu próximo combo será inolvidable",
    "Un boss difícil caerá al primer intento",
    "Vas a encontrar un atajo en un mapa que no conocías",
    "Una partida casual se volverá la mejor del mes",
    "Vas a desbloquear un logro raro pronto",
    "Tu próxima sesión nocturna será memorable",
    "Una nueva skin gratis te llegará por evento",
    "Vas a redescubrir un juego viejo y enamorarte otra vez",
    "Tu equipo carrieará a un noob esta semana",
    "Una build experimental te funcionará perfecto",
    "Vas a encontrar un secret room en un dungeon",
    "Tu próxima partida competitiva será una clase magistral",
    "Una racha de victorias arranca esta noche",
    "Vas a hacer un ace o quadra kill memorable",
    "Tu próximo trade in-game será muy ventajoso",
    "Una update mejorará tu personaje favorito",
    "Vas a probar un género nuevo y te encantará",
    "Tu próxima maratón gamer no tendrá lag",
    "Vas a recibir un buff justo cuando lo necesitabas",
    "Una runa o item raro caerá pronto en tu inventario",
    "Tu equipo encontrará el meta perfecto",
    "Vas a vencer a alguien mejor ranqueado que vos",
    "Tu próxima sesión coop terminará con muchas risas",
    "Una jugada tuya se viralizará en clips",
    "Vas a llegar a la final de un torneo que esperabas",
    "Tu próxima compra in-game valdrá la pena",
    "Una colaboración con otro jugador será explosiva",
    "Vas a romper un récord personal pronto",
    "Tu próxima estrategia ofensiva sorprenderá a todos",
    "Una sesión de práctica te dará un nivel nuevo",
    "Vas a recibir respeto del lobby por una jugada épica",
    "Tu próximo personaje main será uno inesperado",
    "Una jugada de soporte salvará la ronda",
    "Vas a dominar una mecánica que te costaba",
    "Tu próxima partida con amigos se hará legendaria",
    "Una convocatoria a clan o gremio te buscará",
    "Vas a desbloquear contenido oculto sin querer",
    "Tu próximo modo nuevo será tu favorito",
    "Una ofrenda al RNG te dará buenas tiradas",
    "Vas a vencer a un raid que tenías pendiente",
    "Tu próxima estrategia furtiva ganará una partida",
    "Una run te saldrá perfecta de principio a fin",
    "Vas a tener una sesión de farm súper rentable",
    "Tu próxima conexión a internet será impecable",
    "Una nueva amistad gamer te durará años",
    "Vas a probar un juego retro y te quedarás horas",
    "Tu próxima partida online no tendrá rage quits",
    "Una build solo carry te funcionará a la perfección",
    "Vas a entender un mecanismo del juego que ignorabas",
    "Tu próxima ranked te dejará en racha",
    "Una recompensa diaria valdrá oro pronto",
    "Vas a clavar un parry imposible en boss",
    "Tu próxima edición especial llegará a buen precio",
    "Una colaboración cross-game te sorprenderá positivamente",
]
assert len(GAMING) >= 60, len(GAMING)

# ── SOCIAL (45) ────────────────────────────────────────────────────────
SOCIAL = [
    "Tu próxima publicación tendrá engagement explosivo",
    "Vas a ganar seguidores nuevos sin buscarlo",
    "Una persona influyente te recomendará pronto",
    "Tu siguiente video o reel se viralizará",
    "Vas a recibir comentarios cariñosos en tus posts",
    "Una colaboración con otro creador te potenciará",
    "Tu energía hoy va a contagiar a quien te lea",
    "Vas a unirte a un grupo nuevo lleno de buena vibra",
    "Una persona del pasado te buscará con cariño",
    "Tu carisma estará en su mejor momento esta semana",
    "Vas a recibir una invitación social que aceptarás encantado",
    "Una historia que subas te traerá un mensaje especial",
    "Vas a recuperar una amistad valiosa muy pronto",
    "Tu humor brillará en una reunión próxima",
    "Una conversación grupal te dejará con energía",
    "Vas a sentirte muy querido por un mensaje espontáneo",
    "Una invitación a evento te abrirá nuevas relaciones",
    "Tu networking traerá frutos en pocos días",
    "Vas a hacer reír a varias personas esta semana",
    "Una persona te buscará para confiar un secreto",
    "Vas a tener una velada social inolvidable",
    "Tu siguiente fiesta o salida será épica",
    "Una persona admirada querrá hablar contigo",
    "Vas a romper el hielo con alguien tímido",
    "Tu sentido del humor te abrirá una puerta nueva",
    "Una persona te invitará a un proyecto creativo",
    "Vas a sentirte parte de algo más grande",
    "Tu energía social atraerá personas afines",
    "Una conversación al azar te alegrará el día",
    "Vas a hacer match con una buena amistad nueva",
    "Tu cumpleaños o evento personal será celebrado a lo grande",
    "Una persona te confesará admiración por tu trabajo",
    "Vas a coincidir con alguien por casualidad y será mágico",
    "Tu próxima cena con amigos quedará en la memoria",
    "Una persona se reconciliará contigo pronto",
    "Vas a sentir cariño desde lugares inesperados",
    "Tu próximo selfie tendrá muchos likes",
    "Una salida de último momento será la mejor del mes",
    "Vas a estar invitado a un evento exclusivo",
    "Tu lado más auténtico ganará nuevos amigos",
    "Una persona muy distinta a vos te complementará perfecto",
    "Vas a tener un mensaje grupal lleno de risas",
    "Tu próximo viaje en grupo será inolvidable",
    "Una persona discreta te apoyará en silencio",
    "Vas a recibir un audio largo lleno de cariño",
]
assert len(SOCIAL) >= 45, len(SOCIAL)

# ── CREATIVE (45) ──────────────────────────────────────────────────────
CREATIVE = [
    "Tu próxima idea creativa cambiará tu vida",
    "Vas a escribir, dibujar o grabar algo memorable",
    "Una inspiración nocturna te dejará sin sueño",
    "Tu próximo proyecto artístico tendrá éxito",
    "Vas a redescubrir una pasión olvidada",
    "Una colaboración creativa te explotará la cabeza",
    "Tu siguiente pieza recibirá mucho amor",
    "Vas a destrabar un bloqueo creativo esta semana",
    "Una idea simple se transformará en algo grande",
    "Tu lado artístico te traerá ingresos inesperados",
    "Vas a probar una técnica nueva que dominarás rápido",
    "Una pintura, foto o video tuyo será viral",
    "Tu mente estará llena de buenas ideas estos días",
    "Vas a inspirar a otra persona sin proponértelo",
    "Una herramienta nueva potenciará tu creatividad",
    "Tu siguiente storytelling conmoverá a alguien",
    "Vas a tener un destello de genialidad mañana",
    "Una canción que escuches te disparará un proyecto",
    "Tu próxima sesión creativa volará en horas",
    "Vas a animarte a publicar algo que tenías guardado",
    "Una crítica constructiva te llevará al siguiente nivel",
    "Tu portfolio crecerá con algo que harás esta semana",
    "Vas a vender un trabajo creativo por más de lo pensado",
    "Una idea para un libro o canción aparecerá clara",
    "Tu próxima sesión de fotos saldrá increíble",
    "Vas a colaborar con alguien admirado",
    "Una clase o tutorial cambiará tu técnica",
    "Tu próxima creación tendrá un toque personal único",
    "Vas a romper tu propia regla y eso será el éxito",
    "Una idea de noche se va a hacer realidad rápido",
    "Tu manera de ver el mundo inspirará a otros",
    "Vas a conocer a un creador que admiras",
    "Una nueva paleta, sonido o estilo te enamorará",
    "Tu próxima edición de video saldrá perfecta",
    "Vas a desbloquear un estilo propio reconocible",
    "Una vieja libreta tuya esconde un proyecto vivo",
    "Tu siguiente diseño impresionará a un cliente",
    "Vas a animarte a hacer un live creativo",
    "Una serie tuya se volverá viral en poco tiempo",
    "Tu próximo arte tendrá comentarios cariñosos",
    "Vas a improvisar y resultará espectacular",
    "Una historia personal será tu próximo proyecto",
    "Tu próxima publicación creativa romperá récords personales",
    "Vas a darle a tu marca personal un giro brillante",
    "Una colaboración online te abrirá puertas nuevas",
]
assert len(CREATIVE) >= 45, len(CREATIVE)

# ── MYSTERY (45) ───────────────────────────────────────────────────────
MYSTERY = [
    "Una pista importante aparecerá entre líneas hoy",
    "Una coincidencia hoy es en realidad una señal",
    "El cosmos te está enviando un mensaje muy claro",
    "Una persona del pasado tiene una respuesta que necesitas",
    "Vas a sentir un déjà vu que vale la pena anotar",
    "Una sincronía aparecerá si prestas atención al reloj",
    "Un sueño te revelará algo importante esta semana",
    "Una intuición fuerte te salvará de un error",
    "Vas a entender de pronto algo que llevaba meses confuso",
    "Un objeto perdido reaparecerá en un lugar inesperado",
    "Una vibración rara en la mañana es una advertencia útil",
    "Vas a descubrir un secreto que te hará reír",
    "Una persona va a confesar algo escondido",
    "Una palabra repetida tres veces es la pista",
    "Vas a notar señales en los sueños esta semana",
    "Una corriente de aire fría es un mensaje de protección",
    "Vas a ver una luz parpadear en el momento exacto",
    "Una canción aparecerá tres veces y trae mensaje",
    "Vas a recibir una respuesta en forma de coincidencia",
    "Una vieja foto contiene una pista que ignorabas",
    "Tu intuición no se equivoca esta vez",
    "Vas a soñar con alguien que después aparecerá",
    "Una fecha vista al azar es importante para ti",
    "Vas a abrir un libro al azar y encontrar la respuesta",
    "Una persona desconocida te dará un mensaje cifrado",
    "Vas a sentir algo flotando en el ambiente, no es miedo",
    "Una persona sensible te leerá la mente sin querer",
    "Vas a recordar algo que tenías olvidado a propósito",
    "Una serie de números te seguirá unos días",
    "Vas a percibir presencias suaves en tu casa",
    "Una pluma cruzará tu camino y trae buen augurio",
    "Vas a notar una mariposa cuando pienses en alguien",
    "Una conversación captada al pasar es una respuesta",
    "Vas a sentir un escalofrío al confirmar una verdad",
    "Una persona reaparecerá con un mensaje espiritual",
    "Vas a leer entre líneas y descubrir lo importante",
    "Una sincronía con un reloj te marcará una decisión",
    "Vas a notar la presencia de alguien querido fallecido",
    "Una vibración positiva te avisará de buenas noticias",
    "Vas a sentir un corazonazo, hazle caso siempre",
    "Una baraja del tarot personal te resultará útil",
    "Vas a tener un sueño tan claro que parecerá real",
    "Una persona soñará contigo esta misma noche",
    "Vas a percibir la verdad sin que te la digan",
    "Una señal en el cielo o nube te marcará el día",
]
assert len(MYSTERY) >= 45, len(MYSTERY)

# ── HUMOR (45) ─────────────────────────────────────────────────────────
HUMOR = [
    "Hoy te vas a reír de algo absurdo en la calle",
    "Un meme te va a explotar la risa esta semana",
    "Vas a hacer un chiste que va a quedar para siempre",
    "Una conversación en el baño será la más graciosa del mes",
    "Vas a tropezar con algo invisible en público",
    "Una caída tonta te dará una historia para contar",
    "Vas a confundir a alguien con otra persona y será épico",
    "Tu próximo audio enviado por error te avergonzará rico",
    "Una autocorrección te hará pasar un papelón leve",
    "Vas a reírte solo en la calle, no te preocupes",
    "Un chiste viejo tuyo va a revivir esta semana",
    "Una mascota te va a dejar en ridículo de manera adorable",
    "Vas a contar una anécdota mil veces porque es buenísima",
    "Un video te dejará sin aire de tanta risa",
    "Vas a inventar una palabra que se quedará entre amigos",
    "Una cara graciosa tuya quedará inmortalizada en foto",
    "Vas a olvidar el nombre de alguien justo cuando te saluda",
    "Un fail menor te dará anécdota para meses",
    "Vas a reírte tan fuerte que te van a oír los vecinos",
    "Un audio de WhatsApp se reproducirá en momento incómodo",
    "Vas a sufrir un brain freeze en una conversación",
    "Una cuenta nueva en redes te dará risa varias veces",
    "Vas a hacer una mueca involuntaria en una foto importante",
    "Un autocorrector va a cambiar la palabra clave por una rara",
    "Vas a soltar una risa floja en momento serio",
    "Un audio doble velocidad cambiará tu día",
    "Vas a contar mal un chiste y será más gracioso aún",
    "Una notificación llegará en el peor momento gracioso",
    "Vas a confundir el nombre de un amigo en grupo",
    "Una historia tuya se volverá legendaria entre amigos",
    "Vas a tropezar con tus propios pies sin razón",
    "Un familiar te va a recordar algo vergonzoso de niño",
    "Vas a saludar a alguien que no era para ti",
    "Una llamada accidental terminará en buena conversación",
    "Vas a escuchar un audio antiguo tuyo y no te reconocerás",
    "Una palabra mal pronunciada te perseguirá por días",
    "Vas a explicar algo simple de manera demasiado complicada",
    "Una mascota va a aparecer en un live tuyo",
    "Vas a quedarte trabado con una palabra al hablar",
    "Un emoji mal puesto cambiará el sentido del mensaje",
    "Vas a reírte de un meme que no entendés del todo",
    "Una historia random tuya tendrá éxito viral",
    "Vas a reírte sin parar en pleno silencio incómodo",
    "Un sticker absurdo se va a volver tu marca personal",
    "Vas a despertar con cara de meme y no querrás verla",
]
assert len(HUMOR) >= 45, len(HUMOR)

# ── STREAM (30) ────────────────────────────────────────────────────────
STREAM = [
    "Tu próximo stream tendrá récord de viewers",
    "Un super donador va a aparecer pronto",
    "Vas a sumar nuevos seguidores este live",
    "Una raid te va a dar un boost gigante",
    "Tu próximo highlight saldrá viral en TikTok",
    "Una colaboración con otro streamer te potenciará",
    "Vas a recibir muchos likes en tu próximo live",
    "Tu chat estará especialmente activo esta semana",
    "Una donación inesperada te emocionará",
    "Vas a hacer un clutch en stream que se hará famoso",
    "Tu energía conectará con la audiencia como nunca",
    "Una nueva moderación te traerá calma al chat",
    "Vas a probar un formato nuevo y funcionará",
    "Una sesión maratónica romperá tu récord personal",
    "Tu próximo set up mejorará la calidad del stream",
    "Una persona de tu chat se convertirá en gran amistad",
    "Vas a recibir un sub regalado por sorpresa",
    "Un evento especial te traerá viewers nuevos",
    "Tu próxima miniatura tendrá alto CTR",
    "Una invitación a un evento de creadores te llegará",
    "Vas a recuperar viewers que habías perdido",
    "Tu próxima partida en vivo será comentada por meses",
    "Un sponsor te buscará para una colaboración pronto",
    "Vas a recibir mensajes muy cariñosos en chat",
    "Tu siguiente live tendrá menos lag que nunca",
    "Una rifa o sorteo te dará éxito instantáneo",
    "Vas a probar una cámara o luz nueva con buen resultado",
    "Tu próximo overlay enamorará al chat",
    "Una nueva categoría de stream te traerá nuevos fans",
    "Vas a tener una noche épica de stream esta semana",
]
assert len(STREAM) >= 30, len(STREAM)

# ── LUCK (30) ──────────────────────────────────────────────────────────
LUCK = [
    "La suerte te acompañará todo el día",
    "Vas a ganar en algo de azar pronto",
    "Una racha buena empieza este mismo momento",
    "Tu próximo número de la suerte será 7",
    "Vas a encontrar dinero en un bolsillo viejo",
    "Una oferta perfecta aparecerá justo a tiempo",
    "Vas a ser el ganador inesperado de un sorteo",
    "Tu nombre aparecerá en una lista premiada",
    "Una sincronía te traerá buena suerte el martes",
    "Vas a resolver algo difícil con suerte pura",
    "Tu trébol invisible te acompaña hasta el viernes",
    "Una racha en el celular te traerá suerte digital",
    "Vas a llegar justo a tiempo a algo importante",
    "Una cola se acortará mágicamente para ti",
    "Vas a evitar un accidente menor por suerte",
    "Tu siguiente apuesta o juego pequeño será ganador",
    "Una persona afortunada te transmitirá su buena vibra",
    "Vas a recibir una invitación gratis a algo costoso",
    "Tu nombre será el elegido en un sorteo de redes",
    "Una promo perfecta caerá en tu mano hoy",
    "Vas a tener un día con todas las luces verdes",
    "Tu próximo intento te saldrá a la primera",
    "Una persona te abrirá la puerta de un evento exclusivo",
    "Vas a coincidir con alguien clave por pura suerte",
    "Tu intuición te dirá el número ganador",
    "Una carta del tarot te marcará un mes increíble",
    "Vas a tener un golpe de fortuna antes del fin de mes",
    "Una serie de coincidencias afortunadas se desatará",
    "Tu energía de hoy atraerá rifas y premios",
    "Vas a estar en el lugar correcto en el momento perfecto",
]
assert len(LUCK) >= 30, len(LUCK)

# ── WISDOM (30) ────────────────────────────────────────────────────────
WISDOM = [
    "El que se conoce a sí mismo, no necesita aprobación",
    "La calma es más eficaz que mil estrategias",
    "Quien aprende del silencio, nunca queda sin respuesta",
    "El que perdona se libera primero",
    "La sabiduría es saber cuándo callar",
    "Cada error bien usado es un maestro",
    "El que respeta su tiempo, respeta su vida",
    "La paz se construye, no se encuentra",
    "El que escucha, gobierna su mente",
    "Tu integridad es tu activo más rentable",
    "Quien siembra paciencia, cosecha milagros",
    "La gratitud transforma cada día común",
    "El que ama sin condiciones, vive sin cargas",
    "La humildad abre puertas que la fuerza no rompe",
    "El que se ríe de sí mismo, jamás es vencido",
    "Tu palabra vale más que cualquier promesa firmada",
    "El que sabe esperar, evita perder dos veces",
    "La verdad llega siempre, aunque tarde",
    "El que controla sus impulsos, controla su destino",
    "La generosidad multiplica más que la riqueza",
    "El que mide sus palabras, multiplica su poder",
    "La constancia rompe paredes que la pasión solo araña",
    "El silencio bien usado es la mejor respuesta",
    "El que cuida sus pensamientos cuida su realidad",
    "La compasión es la inteligencia del alma",
    "El que vive con propósito, no necesita prisa",
    "Tu mejor maestro será siempre tu peor crisis",
    "La sencillez es la sofisticación máxima",
    "El que se rinde aprende, el que se levanta crece",
    "La calidad de tus preguntas define tu vida",
]
assert len(WISDOM) >= 30, len(WISDOM)

# ── GROSERA (80) — sarcástica/burlona, sin lenguaje prohibido TikTok ──
GROSERA = [
    "Hoy hasta la sombra te va a hacer bullying",
    "Tus planes para hoy: nada, y no lo vas a cumplir",
    "El universo te mandó saludos, dice que te enfoques porfa",
    "Tu fortuna dice: probá levantarte antes del mediodía",
    "Hoy hasta tu wifi tiene mejor estabilidad emocional que vos",
    "Las estrellas te recomiendan callar, descansa esa boca",
    "El destino dice: quizás un baño no estaría mal hoy",
    "Tu suerte está de licencia, vuelve la próxima semana",
    "Hoy todo va a salir bien, mentira",
    "El universo no responde a tus mensajes, dejá de insistir",
    "Tu fortuna pide vacaciones de vos esta semana",
    "Las estrellas dicen que ordenes el cuarto, todas las dueñas tienen razón",
    "Tu próxima decisión será mala, pero será tuya, felicidades",
    "El cosmos te observa y suspira fuerte",
    "Hoy hasta el horóscopo te dejó en visto",
    "Tu energía hoy es de cargador desconectado",
    "Las cartas dicen: andá a tomar agua antes de hablar",
    "Tu fortuna llega tarde como vos al trabajo",
    "El destino te recomienda menos historias y más acción",
    "Las estrellas piden que dejes de quejarte por un día",
    "Tu suerte es como tus ahorros: indetectable",
    "El cosmos votó y opina que dejes de scrollear",
    "Hoy tu peor enemigo serás vos mismo, como siempre",
    "Tu fortuna dice: salí de la cama antes que te crezcan raíces",
    "El universo te bendice con paciencia para aguantarte",
    "Las estrellas se alinearon para darte un consejo: lavate los dientes",
    "Tu próximo gran logro será no quedarte dormido en una reunión",
    "El destino dice que hoy te merecés un descanso, todos los días igual",
    "Tu suerte está en mantenimiento, intentá mañana",
    "Hoy el sol salió, pero vos no, eso es un problema",
    "El cosmos te recuerda que el celular también necesita descansar",
    "Las cartas dicen: tu vida sería mejor con menos drama",
    "Tu fortuna pidió cambio de viewer, no se lo permitieron",
    "El destino aplaude tu voluntad de hacer todo a último momento",
    "Las estrellas opinan que hoy tu mejor look es no salir",
    "Tu suerte hoy alcanza para encontrar la alpargata",
    "El universo dice: gracias por existir, pero a la distancia",
    "Hoy tu mejor decisión será no decidir nada importante",
    "Tu fortuna se actualiza cada Black Friday, esperá",
    "El cosmos te manda fuerza, vas a necesitarla aunque no la quieras",
    "Las cartas dicen: bajale dos rayitas a tu nivel de drama",
    "Tu próxima compra impulsiva ya está prevista por tu banco",
    "El destino te avisa: ese ex no era buena idea, ya sabés",
    "Las estrellas piden que dejes a tu familia comer en paz",
    "Tu suerte dice presente, pero firma con seudónimo",
    "El universo está orgulloso de vos, en escala muy reducida",
    "Hoy es buen día para callarte estratégicamente",
    "Tu fortuna mejoraría si pagaras tus cuentas a tiempo",
    "El cosmos opina que tus playlists merecen un upgrade urgente",
    "Las cartas dicen: tu autocrítica se le fue de las manos al universo",
    "Tu próximo selfie va a necesitar editar mucho, sorry",
    "El destino sugiere: pensá antes de mandar ese audio largo",
    "Las estrellas piden que dejes de stalkear a esa persona",
    "Tu suerte hoy es como tus ganas de bañarte: variable",
    "El universo te observa con cariño y mucha resignación",
    "Hoy hasta tu signo zodiacal te bloqueó",
    "Tu fortuna llegó, pero solo puede ser en cuotas",
    "El cosmos pide: bajá la guardia y subí la actitud",
    "Las cartas dicen: un día sin drama no te mata, probá",
    "Tu próxima cita necesita un milagro, pero vamos en buen camino",
    "El destino dice: dale, andá a hacer ejercicio, dos minutos cuentan",
    "Las estrellas piden que respondas el WhatsApp de tu mamá",
    "Tu suerte es alta hoy, pero la batería del cel está al 3 por ciento",
    "El universo te pide perdón por tu última decisión amorosa",
    "Hoy los astros te dan un regalo: una segunda oportunidad para callarte",
    "Tu fortuna pide refresco, así como vos pides like",
    "El cosmos opina que hoy podrías tomar agua sin que te lo recuerden",
    "Las cartas dicen: el problema no son los demás, sos vos",
    "Tu próximo enojo será injustificado, pero igual lo vas a sostener",
    "El destino te invita a un gran proyecto: ordenar el mail",
    "Las estrellas piden que pares de juzgar y empieces a vivir",
    "Tu suerte mejoraría si dejás de preguntarle al horóscopo",
    "El universo está lleno de señales, vos lleno de excusas",
    "Hoy la comida casera te va a saber mejor que tus tweets",
    "Tu fortuna está bien, lo que está mal es el wifi de tu vecino",
    "El cosmos sugiere: dejá la procrastinación por un solo día",
    "Las cartas dicen: tu actitud de hoy es de domingo a la noche",
    "Tu próximo plan brillante necesita un plan B y uno C",
    "El destino te manda un abrazo, devolvé los libros prestados",
    "Las estrellas opinan que tu humor hoy es internacional, todos lo notan",
    "Tu suerte te abandonó por un rato, igual fingí que está",
]
assert len(GROSERA) >= 80, len(GROSERA)


def main() -> None:
    out = {
        "intro_templates": INTROS,
        "good": GOOD,
        "bad": BAD,
        "neutral": NEUTRAL,
        "specific": SPECIFIC,
        "philosophical": PHILOSOPHICAL,
        "love": LOVE,
        "money": MONEY,
        "health": HEALTH,
        "work": WORK,
        "gaming": GAMING,
        "social": SOCIAL,
        "creative": CREATIVE,
        "mystery": MYSTERY,
        "humor": HUMOR,
        "stream": STREAM,
        "luck": LUCK,
        "wisdom": WISDOM,
        "grosera": GROSERA,
    }
    json.dump(out, sys.stdout, ensure_ascii=False, indent=2)


if __name__ == "__main__":
    main()
